import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ShopProvider } from "@/context/ChomContext";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chomp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body id="root" suppressHydrationWarning={true} className={font.className}>
          <ShopProvider>
            {children}
          </ShopProvider>
      </body>
    </html>
  );
}
